export const availableTags = [
  "Array",
  "String",
  "Hash Table",
  "Dynamic Programming",
  "Math",
  "Sorting",
  "Greedy",
  "Database",
  "Binary Search",
  "Tree",
  "Depth-First Search",
  "Binary Tree",
  "Breadth-First Search",
  "Two Pointers",
  "Stack",
  "Graph",
];
export const iconMap = {
  array: "🔢",
  string: "📝",
  "hash table": "🗂️",
  "dynamic programming": "⚡",
  math: "➗",
  sorting: "📊",
  greedy: "💰",
  database: "💾",
  "binary search": "🔎",
  tree: "🌳",
  "depth-first search": "🧭",
  "binary tree": "🌲",
  "breadth-first search": "🚶",
  "two pointers": "👯",
  stack: "📚",
  graph: "🕸️",
};
